### ISSUE TITLE
[Bug]: Cannot add a profile (can't use the extension)

### ISSUE THREAD

**Issue by devpro** [outscale/vscode-osc-viewer#84]
### Plugin version

0.6.1

### VSCode version

1.79.2

### Error Output

Nothing displayed

### Expected Behavior

In osc-viewer extension, from the top menu, click on Add, I try to enter anything and when I click on Enter I can move to next step and at the end complete the profile so I can use the extension.

### Actual Behavior

In osc-viewer extension, from the top menu, click on Add, I try to enter anything and when I click on Enter nothing happens.

### Steps to Reproduce

From a Windows 10 workstation, in osc-viewer Visual Studio extension, from the top menu, click on Add, enter any string, click on Enter.

**Comment by outscale-mdr** [comment]
Hello @devpro,

We cannot reporoduce this issue, could you test again with the latest version and reopen the issue in case of errors.

Thank you !
