### ISSUE TITLE
Support of osc-cost

### ISSUE THREAD

**Issue by outscale-mdr** [outscale/vscode-osc-viewer#93]
## Description

[osc-cost](https://github.com/outscale/osc-cost) is a tools to estimate cloud consumption in Outscale. It would be great if the plugin uses the tool to display the estimation directly.

## Features
- [ ] Display the price per account, per object and individually
   - Here are examples:
<img width="208" alt="Capture d’écran 2023-10-26 à 14 31 37" src="https://github.com/outscale/vscode-osc-viewer/assets/91073311/bda40d33-f43e-426d-814f-28d1700edbbb">
<img width="208" alt="Capture d’écran 2023-10-26 à 14 32 03" src="https://github.com/outscale/vscode-osc-viewer/assets/91073311/109ed319-b27b-444f-8401-f96b8e235e5f">

 - [ ] If we could use these badges
![image](https://github.com/outscale/vscode-osc-viewer/assets/91073311/bddb370d-2d0d-408e-adeb-0404ebc87ee1)

- Customizable (Configuration)
  - [ ]  disable by default
  - [ ] activate for all profiles or per profile
- [ ] Ask the user if it wants to download the binary osc-cost (like tools for go for example)
- [ ] Asynchronous, the retrieval should not add display latency, the estimation will be displayed when it arrives and we will not wait

**Comment by stephrobert** [comment]
We need it !
